### ISSUE TITLE
Can we make `output` optional, to save some keystrokes?

### ISSUE THREAD

**Issue by saneef** [hankchizljaw/gorko#14]
The `'output': 'standard'` could be the default value. And, we can  override with ` 'output': 'responsive'` to generate responsive class names.

```scss
$gorko-config: (
  "bg": (
    'items': 'color',
    'css-vars': true,
    'output': 'standard', // 👋  'standard' ≈ 'default'
    'property': 'background-color'
  ),
  "breakpoints": (
    // ...
  )
);

```

Or, is there any specific reason it is kept mandatory? Like, to skip a generating a set when `output` is `null`.

**Comment by Andy-set-studio** [comment]
Yeh it's used in the processor and I'd rather have clarity than save a couple of keystrokes 👍
