### ISSUE TITLE
Allow for generating utility classes that do more than one thing

### ISSUE THREAD

**Issue by mark-reason** [hankchizljaw/gorko#22]
So to cut down the length of my HTML class attribute values it would be good if I could add a pad-y class that deals with the top and bottom instead of using both pad-t and pad-b.

**Comment by Andy-set-studio** [comment]
It's a good idea! I'm just worried that it could over-complicate things, though, so more thought definitely needs to go into it.

One way to fix your specific issue would be to use `padding-block`, a bit like [I did here](https://github.com/GoogleChrome/web.dev/blob/main/src/scss/_config.scss#L122). 

I'll close this for now and keep it under consideration.
