### ISSUE TITLE
Issue with generate utility classes in 0.7.1

### ISSUE THREAD

**Issue by smzr** [hankchizljaw/gorko#23]
When using `$generate-utility-classes: false;` before importing gorko, the utility classes were still showing on my page.
I switched to 0.6.0 and using the same code it now removes the utility classes as expected.

It could be caused by #21

**Comment by Andy-set-studio** [comment]
Thanks for reporting this. Is this something that can be reproduced on a fresh project?

**Comment by smzr** [comment]
I've been able to reproduce the issue on a fresh project.
It seems to happen when I set the gorko config to create css variables for my colours with 0.7.1
```scss
'css-vars': (
  'color': $gorko-colors
),
```
I was incorrect with the original issue, it's not generating every utility class but it will generate the css vars when using `$generate-utility-classes: false;` 
However, it does not do this if I use 0.6.0

A quick way to reproduce this issue is to download the files from [eleventy from scratch](https://piccalil.li/course/learn-eleventy-from-scratch/lesson/30/) then update gorko to 0.7.1 and edit the config to generate css variables. If you then inspect the home page you can see the color variables generated twice

**Comment by Andy-set-studio** [comment]
Ah, I think I get what's going on. Try setting `$generate-css-vars = false;` which was a new update to `0.7.1`. [More at the end of this section](https://github.com/andy-piccalilli/gorko#using-css-custom-properties).

**Comment by Andy-set-studio** [comment]
I added that because I had a similar requirement where multiple CSS files were generated and I only wanted the Custom Properties to be generated once

**Comment by smzr** [comment]
Ah I see, that makes sense. Will apply these changes to my stylesheets, thanks!

**Comment by Andy-set-studio** [comment]
No worries at all. It is a very new thing, so easily missed too :)
