### ISSUE TITLE
Design tokens

### ISSUE THREAD

**Issue by djmtype** [hankchizljaw/gorko#7]
@hankchizljaw This isn't an issue, but a compliment. 

I think one of the most underrated gems about Hylia was the use of design tokens which parsed JSON to SCSS. It would also turn out a simple styleguide page. And if you were managing Hylia with Forestry, Forestry would display the color tokens as swatches, not just hex codes. 

It was perfect when utilizing something like Fractal.build would be overkill. It relied on your Stalfos – which looks like the fetus that partly evolved into Gorko. 

Any plans on extending Gorko into a low-level design system?

**Comment by Andy-set-studio** [comment]
Thanks for the kind words about Hylia! Probably not going to extend gorko quite like that though because it's more a tool to help with working with tokens, rather than a full blown system. I see it as a complimentary thing, rather than the be-all :)
